/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElRow: typeof import('element-plus/es')['ElRow']
    Empty: typeof import('./../src/components/common/Empty/index.vue')['default']
    GLBgIcon: typeof import('./../src/components/common/GLBgIcon.vue')['default']
    GLIcon: typeof import('./../src/components/common/GLIcon.vue')['default']
    ResizeBox2: typeof import('./../src/components/common/resizeBox2.vue')['default']
    ResizeVBox: typeof import('./../src/components/common/resizeVBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./../src/components/Versions.vue')['default']
    WindowControl: typeof import('./../src/components/WindowControl/index.vue')['default']
  }
}
